export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_SIGN_STATE = 'SET_SIGN_STATE';

export const SET_REGISTER_STATE = 'SET_REGISTER_STATE';

export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';

export const ADD_ITEM = 'ADD_ITEM';

export const CLEAR_ITEM = 'CLEAR_ITEM';

export const REMOVE_ITEM = 'REMOVE_ITEM';