export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_REGISTER_IS_WRONG = 'SET_IS_WRONG';

export const SET_REGISTER_IS_CORRECT = 'SET_IS_CORRECT';

export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';

export const ADD_ITEM = 'ADD_ITEM';

export const CLEAR_ITEM = 'CLEAR_ITEM';

export const REMOVE_ITEM = 'REMOVE_ITEM';

export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';

export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';

export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE';

export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';

export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';

export const SIGN_OUT_START = 'SIGN_OUT_START';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const CLEAR_CART = 'CLEAR_CART';

export const SIGN_UP_START = 'SIGN_UP_START';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const CHANGE_REGISTER_FORM_DATA = 'CHANGE_REGISTER_FORM_DATA';

export const SET_SIGN_IN_IS_WRONG = 'SET_SIGN_IN_IS_WRONG';

export const SET_SIGN_IN_IS_CORRECT = 'SET_SIGN_IN_IS_CORRECT';

export const CHANGE_SIGN_IN_FORM_DATA = 'CHANGE_SIGN_IN_FORM_DATA';

export const SHOW_ALERT = 'SHOW_ALERT';

export const CLOSE_ALERT = 'CLOSE_ALERT';

export const SET_ALERT_TEXT = 'SET_ALERT_TEXT';